
export const GET_SERVICES_DATA_REQUEST = 'GET_SERVICES_DATA_REQUEST';
export const GET_SERVICES_DATA_SUCCESS = 'GET_SERVICES_DATA_SUCCESS';
export const GET_SERVICES_DATA_ERROR = 'GET_SERVICES_DATA_ERROR';
export const GET_HARDWARE_DATA_REQUEST = 'GET_HARDWARE_DATA_REQUEST';
export const GET_HARDWARE_DATA_SUCCESS = 'GET_HARDWARE_DATA_SUCCESS';
export const GET_HARDWARE_DATA_ERROR = 'GET_HARDWARE_DATA_ERROR';
export const GET_IIS_APPS_REQUEST = 'GET_IIS_APPS_REQUEST';
export const GET_IIS_APPS_SUCCESS = 'GET_IIS_APPS_SUCCESS';
export const GET_IIS_APPS_ERROR = 'GET_IIS_APPS_ERROR';

export const GET_IIS_TOGGLE_REQUEST = 'GET_IIS_TOGGLE_REQUEST';
export const GET_IIS_TOGGLE_SUCCESS = 'GET_IIS_TOGGLE_SUCCESS';
export const GET_IIS_TOGGLE_ERROR = 'GET_IIS_TOGGLE_ERROR';
