
export const GET_TABLE_DATA_REQUEST = 'GET_TABLE_DATA_REQUEST';
export const GET_TABLE_DATA_SUCCESS = 'GET_TABLE_DATA_SUCCESS';
export const GET_TABLE_DATA_ERROR = 'GET_TABLE_DATA_ERROR';
export const GET_SERVICES_DATA_REQUEST = 'GET_SERVICES_DATA_REQUEST';
export const GET_SERVICES_DATA_SUCCESS = 'GET_SERVICES_DATA_SUCCESS';
export const GET_SERVICES_DATA_ERROR = 'GET_SERVICES_DATA_ERROR';
