export const GET_SERVICES_DATA_REQUEST = "GET_SERVICES_DATA_REQUEST";
export const GET_SERVICES_DATA_SUCCESS = "GET_SERVICES_DATA_SUCCESS";
export const GET_SERVICES_DATA_ERROR = "GET_SERVICES_DATA_ERROR";
export const GET_HARDWARE_DATA_REQUEST = "GET_HARDWARE_DATA_REQUEST";
export const GET_HARDWARE_DATA_SUCCESS = "GET_HARDWARE_DATA_SUCCESS";
export const GET_HARDWARE_DATA_ERROR = "GET_HARDWARE_DATA_ERROR";
export const GET_IIS_APPS_REQUEST = "GET_IIS_APPS_REQUEST";
export const GET_IIS_APPS_SUCCESS = "GET_IIS_APPS_SUCCESS";
export const GET_IIS_APPS_ERROR = "GET_IIS_APPS_ERROR";

export const GET_IIS_TOGGLE_REQUEST = "GET_IIS_TOGGLE_REQUEST";
export const GET_IIS_TOGGLE_SUCCESS = "GET_IIS_TOGGLE_SUCCESS";
export const GET_IIS_TOGGLE_ERROR = "GET_IIS_TOGGLE_ERROR";

export const GET_IIS_WHITELIST_REQUEST = "GET_IIS_WHITELIST_REQUEST";
export const GET_IIS_WHITELIST_SUCCESS = "GET_IIS_WHITELIST_SUCCESS";
export const GET_IIS_WHITELIST_ERROR = "GET_IIS_WHITELIST_ERROR";

export const GET_IIS_RECYCLE_REQUEST = "GET_IIS_RECYCLE_REQUEST";
export const GET_IIS_RECYCLE_SUCCESS = "GET_IIS_RECYCLE_SUCCESS";
export const GET_IIS_RECYCLE_ERROR = "GET_IIS_RECYCLE_ERROR";

export const DISK_USAGE_REQUEST = "DISK_USAGE_REQUEST";
export const DISK_USAGE_SUCCESS = "DISK_USAGE_SUCCESS";
export const DISK_USAGE_ERROR = "DISK_USAGE_ERROR";

export const TASKS_REQUEST = "TASKS_REQUEST";
export const TASKS_SUCCESS = "TASKS_SUCCESS";
export const TASKS_ERROR = "TASKS_ERROR";

export const TASKS_RUN_REQUEST = "TASKS_RUN_REQUEST";
export const TASKS_RUN_SUCCESS = "TASKS_RUN_SUCCESS";
export const TASKS_RUN_ERROR = "TASKS_RUN_ERROR";

export const SESSIONS_REQUEST = "SESSIONS_REQUEST";
export const SESSIONS_SUCCESS = "SESSIONS_SUCCESS";
export const SESSIONS_ERROR = "SESSIONS_ERROR";

export const SESSIONS_KILL_REQUEST = "SESSIONS_KILL_REQUEST";
export const SESSIONS_KILL_SUCCESS = "SESSIONS_KILL_SUCCESS";
export const SESSIONS_KILL_ERROR = "SESSIONS_KILL_ERROR";

export const ORACLE_REQUEST = "ORACLE_REQUEST";
export const ORACLE_SUCCESS = "ORACLE_SUCCESS";
export const ORACLE_ERROR = "ORACLE_ERROR";

export const TOGGLE_ORACLE_REQUEST = "TOGGLE_ORACLE_REQUEST";
export const TOGGLE_ORACLE_SUCCESS = "TOGGLE_ORACLE_SUCCESS";
export const TOGGLE_ORACLE_ERROR = "TOGGLE_ORACLE_ERROR";

export const SET_NOTE_REQUEST = "SET_NOTE_REQUEST";
export const SET_NOTE_SUCCESS = "SET_NOTE_SUCCESS";
export const SET_NOTE_ERROR = "SET_NOTE_ERROR";

export const GET_SETTINGS_REQUEST = "GET_SETTINGS_REQUEST";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_ERROR = "GET_SETTINGS_ERROR";

export const SET_CLEANER_REQUEST = "SET_CLEANER_REQUEST";
export const SET_CLEANER_SUCCESS = "SET_CLEANER_SUCCESS";
export const SET_CLEANER_ERROR = "SET_CLEANER_ERROR";
